content:
  field_first_name:
    weight: 1
  field_last_name:
    weight: 2
  user_picture:
    type: image
    weight: 0
    settings:
      image_style: thumbnail
      image_link: ''
    third_party_settings: {  }
    label: hidden
