content:
  body:
    settings:
      trim_length: 200
  field_image:
    settings:
      image_style: article_preview
      image_link: content
  field_tags:
    type: entity_reference_label
    weight: 4
    label: hidden
    settings:
      link: false
    third_party_settings: {  }
hidden:
  field_tags: false
