<?php

/**
 * @file
 * Set up the Obio Scenario.
 */

/**
 * Implements hook_install().
 */
function dfs_obio_install() {
  // Enable translation for all of our entities/bundles.
  $entities = [
    'comment' => ['review'],
    'node' => [
      'product',
      'location',
    ],
    'taxonomy_term' => [
      'tags',
    ],
  ];
  df_tools_translation_enable_translation($entities);

  // Import our custom .po files
  df_tools_translation_import_translations('module', 'dfs_obio');
}
